# Generated by Django 5.2.8 on 2025-11-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product/Bot name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('bot_username_or_link', models.CharField(help_text='URL or @username', max_length=500)),
                ('contract_months', models.IntegerField(choices=[(1, '1 month'), (2, '2 months'), (3, '3 months'), (4, '4 months'), (5, '5 months'), (6, '6 months'), (7, '7 months'), (8, '8 months'), (9, '9 months'), (10, '10 months'), (11, '11 months'), (12, '12 months')], default=1, help_text='Contract duration in months')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('renewed', 'Renewed')], default='active', help_text='Product status', max_length=20)),
                ('customer_link', models.CharField(help_text='Telegram username or contact link', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(help_text='Auto-calculated from contract duration')),
                ('last_renewed', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='products_pr_status_041708_idx'), models.Index(fields=['expiry_date'], name='products_pr_expiry__6a0178_idx'), models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx')],
            },
        ),
    ]
